# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-09 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author_ids',
            field=models.ManyToManyField(related_name='a_ids', related_query_name='author_ids', to='management.Author'),
        ),
    ]
